jQuery(document).ready(function($){if($('.five-col-slider').length>0){$('.five-col-slider').owlCarousel({responsiveClass:true,autoWidth:true,items:5,margin:10,nav:true,dots:false,responsive:{0:{onDragged:fixSpacing,},769:{onDragged:function(){return;},}}});}
if($('.blockquote-slider .blockquote-wrapper').length>0){$('.blockquote-slider .blockquote-wrapper').owlCarousel({responsiveClass:true,items:1,nav:true,dots:true,});}
function fixSpacing(event){var element=event.target;$(element).parent().css({paddingLeft:0});};$(window).on('load resize',function(){var h=$('.banner-img').height()/2;$('.story-header').css({paddingBottom:h,marginBottom:h+50});});$(".tooltip_main_content").on("click",function(e){e.preventDefault();var tooltip=$(this).parents('.story_tooltip_class').find('.tooltip_hover_container');console.log(tooltip);$(".tooltip_hover_container").not($(tooltip)).hide();$(tooltip).toggle();if($(tooltip).find('.share-links').length==0){var offset=$(tooltip).offset();if(offset){var left=offset.left;var right=offset.left+$(tooltip).width();}
if($(window).width()<=right){$(tooltip).css({left:$(window).width()-right-43});}
if(left<=0){$(tooltip).css({left:0});}}});$(document).click(function(event){$target=$(event.target);if($target.hasClass("tooltip_main_content")||$target.hasClass("footer-share")){}else if(!$target.hasClass("tooltip_hover_container")&&!$target.parents(".tooltip_hover_container").is(":visible")){$(".tooltip_hover_container").hide();}else if($target.parents(".tooltip_hover_container").length>0&&!$target.parents(".tooltip_hover_container").is(":visible")){$(".tooltip_hover_container").hide();}});$(window).scroll(function(){var scrollwin=$(window).scrollTop();var articleheight=$('.main-content').outerHeight(true)-300;if(scrollwin>=$('.main-content').offset().top){if(scrollwin<=($('.main-content').offset().top+articleheight)){$('.story-footer .progress-bar').css('width',((scrollwin-$('.main-content').offset().top)/articleheight)*100+"%");}else{$('.story-footer .progress-bar').css('width',"100%");}}else{$('.story-footer .progress-bar').css('width',"0px");}});$(window).scroll(function(){var scrollwin=$(window).scrollTop()-550;var articleheight=$('.article-content').height();if(scrollwin>=articleheight){$('.story-footer').hide();}else{if(!$('#paywall').is(':visible')){$('.story-footer').show();}else{$('.story-footer').hide();}}});if($('#paywall').is(':visible')){$('.story-footer, footer').hide();}
$('.accordion-title').on('click',function(e){$('.accordion-card').find('.accordion-content').stop().slideUp();$(this).closest('.accordion-card').find('.accordion-content').stop().slideToggle();$('.accordion-title').not($(this)).removeClass('active');if($(this).hasClass('active')){$(this).removeClass('active');}else{$(this).addClass('active');}});$(".custom-dropdown, .sort-dropdown").selectmenu();$('.comment-thead a').on('click',function(e){$(this).parent().addClass('more-comments');e.preventDefault();$('.show-comment').slideDown();$('.comment-thead').remove();});if($('.nudge-screen-inner .custom-dropdown').length>0){$('.nudge-screen-inner .custom-dropdown').selectmenu({change:function(event,ui){if(ui.item.label.toLowerCase()=="india edition"){$(this).closest('.nudge-screen-inner').find('.india-edition').css('display','flex');$(this).closest('.nudge-screen-inner').find('.south-east-edition').css('display','none');}else if(ui.item.label.toLowerCase()=="SOUTHEAST ASIA edition"){$(this).closest('.nudge-screen-inner').find('.south-east-edition').css('display','flex');$(this).closest('.nudge-screen-inner').find('.india-edition').css('display','none');}}});}
if($('.modal').length>0){$('.modal').modal('hide');}
if($('.articles-overlap-bg').length>0){$('.articles-overlap-bg').waypoint(function(){var height=$(this[0,'element']).parent('.overflowing-articles-wrapper').height();$(this[0,'element']).height(height);$(this[0,'element']).addClass("animate");},{offset:'75%'});}
var loginBoxHeight=$('.login-section').outerHeight(true);if(loginBoxHeight<=100){loginBoxHeight=600;}
var paywallOffsetTop=$('header').outerHeight(true)+$('.story-header').outerHeight(true)+loginBoxHeight+350;$('#paywall').css('top',paywallOffsetTop);$(window).on('load resize',function(){var loginBoxHeight=$('.login-section').outerHeight(true);if(loginBoxHeight<=100){loginBoxHeight=600;}
var paywallOffsetTop=$('header').outerHeight(true)+$('.story-header').outerHeight(true)+loginBoxHeight+350;$('#paywall').css('top',paywallOffsetTop);if($('#paywall').is(':visible')){var heightPaywall=$('#paywall').outerHeight(true)+loginBoxHeight+350;$('.story-article-content').css({height:heightPaywall,overflow:'hidden'});}})
$('.show-story-summary').on('click',function(e){e.preventDefault();$('.story-summary').slideToggle('slow',function(){loginBoxHeight=$('.login-section').outerHeight();if(loginBoxHeight<=100||$(this).text()=='Show Summary'){loginBoxHeight=100;}
paywallOffsetTop=$('header').outerHeight(true)+$('.story-header').outerHeight(true)+loginBoxHeight+400;$('#paywall').animate({top:paywallOffsetTop},'slow');heightPaywall=$('#paywall').outerHeight(true)+loginBoxHeight+340;$('.story-article-content').css({height:heightPaywall});});$(this).text(($(this).text()=='Hide Summary')?'Show Summary':'Hide Summary');});function copyToClipboard(element){var $temp=$("<input>");$("body").append($temp);$temp.val($(element).val()).select();document.execCommand("copy");$temp.remove();}
$('.copylink').on('click',function(){copyToClipboard('.copy-link-field .form-control');});function validateEmail(email){var re=/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return re.test(String(email).toLowerCase());}
if($('.gift-email-story').length>0){$('.gift-email-story').multiple_emails({placeholder:"Enter one or more email addresses"});}
$('.story-footer-nav .closeicon').on('click',function(e){e.preventDefault();$('.story-tooltip .tooltip_hover_container').hide();});$(window).scroll(function(){$('.story-tooltip .tooltip_hover_container').hide();});});