jQuery(document).ready(function($){var pathname=window.location.pathname;var ival=0;var share_count=$('#shared_count').val();if(share_count){ival=share_count;}
var getUrlParameter=function getUrlParameter(sParam){var sPageURL=decodeURIComponent(window.location.search.substring(1)),sURLVariables=sPageURL.split('&'),sParameterName,i;for(i=0;i<sURLVariables.length;i++){sParameterName=sURLVariables[i].split('=');if(sParameterName[0]===sParam){return sParameterName[1]===undefined?true:sParameterName[1];}}};var urlQueryString={};window.location.search.substr(1).split("&").forEach(function(item){urlQueryString[item.split("=")[0]]=item.split("=")[1]});$.fn.multiple_emails=function(options){var defaults={checkDupEmail:true,theme:"Bootstrap",position:"top"};var settings=$.extend({},defaults,options);var deleteIconHTML="";if(settings.theme.toLowerCase()=="Bootstrap".toLowerCase()){deleteIconHTML='<a href="#" class="multiple_emails-close" title="Remove"><span class="glyphicon glyphicon-remove"></span></a>';}else if(settings.theme.toLowerCase()=="SemanticUI".toLowerCase()||settings.theme.toLowerCase()=="Semantic-UI".toLowerCase()||settings.theme.toLowerCase()=="Semantic UI".toLowerCase()){deleteIconHTML='<a href="#" class="multiple_emails-close" title="Remove"><i class="remove icon"></i></a>';}else if(settings.theme.toLowerCase()=="Basic".toLowerCase()){deleteIconHTML='<a href="#" class="multiple_emails-close" title="Remove"><i class="basicdeleteicon">x</i></a>';}
return this.each(function(){var $orig=$(this);var $list=$('<ul class="multiple_emails-ul" />');if($(this).val()!=''&&IsJsonString($(this).val())){$.each(jQuery.parseJSON($(this).val()),function(index,val){$list.append($('<li class="multiple_emails-email"><span class="email_name" data-email="'+val.toLowerCase()+'">'+val+'</span></li>').prepend($(deleteIconHTML).click(function(e){$(this).parent().remove();refresh_emails();e.preventDefault();})));});}
var $input=$('<input type="text" class="multiple_emails-input text-left" placeholder="Enter email addresses separated by commas"/>').on('keyup',function(e){$(this).removeClass('multiple_emails-error');jQuery('.error_email').text('');var input_length=$(this).val().length;var keynum;if(window.event){keynum=e.keyCode;}else if(e.which){keynum=e.which;}
if(keynum==9||keynum==32||keynum==188){display_email($(this),settings.checkDupEmail,'0');}else if(keynum==13){display_email($(this),settings.checkDupEmail,'0');e.preventDefault();}});$("#share_link").click(function(e){e.preventDefault();$('#share_link').parent().addClass('loadingcopactiry');var share_emails=$('#share_emails').val();var multiple_emails=$('.multiple_emails-input').val();function validateEmail(sEmail){var filter=/^((\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*)\s*[,]{0,1}\s*)+$/;if(filter.test(sEmail)){return true;}else{return false;}}
if($('.multiple_emails-input').val()!=''){if((!validateEmail(multiple_emails))){jQuery('.error_email').text('INVALID EMAIL ADDRESS');jQuery('.multiple_emails-input').addClass('multiple_emails-error');jQuery('#share_link').parent().removeClass('loadingcopactiry');}
else{display_email($('.multiple_emails-input'),settings.checkDupEmail,'1');}}
else{if(share_emails.length==0||share_emails.length<3){if(multiple_emails==''){jQuery('.error_email').text('THIS IS REQUIRED FIELD');jQuery('.multiple_emails-input').addClass('multiple_emails-error');jQuery('#share_link').parent().removeClass('loadingcopactiry');}}
else{funSendChildEmail();}}});var $container=$('<div class="multiple_emails-container" />').click(function(){$input.focus();});if(settings.position.toLowerCase()==="top")
$container.append($list).append($input).insertAfter($(this));else
$container.append($input).append($list).insertBefore($(this));function display_email(t,dupEmailCheck,test){var checklength=$(".multiple_emails-ul").find("li").length;var get_share_emails=jQuery('.multiple_emails-input').val();var resval;var share_emails_request={action:'checkExistingChild',get_share_emails:get_share_emails,checklength:checklength};$.post(the_thekentokenization_response_ajax_script.ajaxurl,share_emails_request,function(response){response=response.slice(0,-1).trim();jQuery('#existing_email').val(response);});setTimeout(function(){var arr=t.val().trim().replace(/^,|,$/g,'').replace(/^;|;$/g,'');arr=arr.replace(/"/g,"");arr=arr.split(/[\s,;]+/);var errorEmails=new Array();var pattern=new RegExp(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i);for(var i=0;i<arr.length;i++){if(dupEmailCheck===true&&$orig.val().indexOf(arr[i])!=-1){if(arr[i]&&arr[i].length>0){new function(){var existingElement=$list.find('.email_name[data-email='+arr[i].toLowerCase().replace('.','\\.').replace('@','\\@')+']');existingElement.css('font-weight','bold');setTimeout(function(){existingElement.css('font-weight','');},1500);}();}}
else if(jQuery('#existing_email').val()=='Exist_share'){jQuery('#existing_email').val('');jQuery('p.error_email').text('AN INVITE HAS ALREADY BEEN SENT BY SOMEONE TO THIS EMAIL '+'"'+get_share_emails+'"');jQuery('#share_link').parent().removeClass('loadingcopactiry');}
else if(jQuery('#existing_email').val()=='Exist_user'){jQuery('#existing_email').val('');jQuery('p.error_email').text(get_share_emails+' IS ALREADY REGISTERED IN OUR SYSTEM ');jQuery('#share_link').parent().removeClass('loadingcopactiry');}
else if(jQuery('#existing_email').val()=='Limit_Exceed'){jQuery('#existing_email').val('');jQuery('p.error_email').text('YOU HAVE EXCEEDED YOUR INVITE LIMIT.');jQuery('#share_link').parent().removeClass('loadingcopactiry');}
else if(pattern.test(arr[i])==true){$list.append($('<li class="multiple_emails-email"><span class="email_name" data-email="'+arr[i].toLowerCase()+'">'+arr[i]+'</span></li>').prepend($(deleteIconHTML).click(function(e){$(this).parent().remove();refresh_emails();e.preventDefault();})));var getInvites=$('.invites_main').text();var getInvites_main=parseInt(getInvites)-1;var totalInvites=parseInt(getInvites_main)-parseInt(checklength);$('.invites_left').text(totalInvites);if(test==='1'||test===1){setTimeout(function(){funSendChildEmail();},5000);}}else{errorEmails.push(arr[i]);}}
if(errorEmails.length>0){t.val(errorEmails.join("; ")).addClass('multiple_emails-error');}else{t.val("");refresh_emails();}},1500);}
function funSendChildEmail(){var share_emails=$('#share_emails').val();var multiple_emails=$('.multiple_emails-input').val()
array=JSON.parse('['+share_emails+']'),share_emails=array.map(function(a){return a;}).join();var data={action:'anniversaryChildEmailsRequest',share_emails:share_emails};$.post(the_thekentokenization_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();if(response=='Mail_Send'){$('.loading-button.send-invite').removeClass('loadingcopactiry');jQuery('#anniversary-child-mail-success').modal('show');hash=window.location.hash;if(hash=='#plans-faux'){window.location.reload(true);}
else{window.location.href=window.location.href+"#plans-faux";window.location.reload(true);}}});}
function refresh_emails(){var emails=new Array();var container=$orig.siblings('.multiple_emails-container');container.find('.multiple_emails-email span.email_name').each(function(){emails.push($(this).html());});$orig.val(JSON.stringify(emails)).trigger('change');}
function IsJsonString(str){try{JSON.parse(str);}catch(e){return false;}
return true;}
return $(this).hide();});};$('#AnniversaryNotification a.open-login-now-modal').click(function(){jQuery('#AnniversaryNotification').modal('hide');});if(urlQueryString.anniversary_code&&!urlQueryString.accountCreated){var ActivationCode=urlQueryString.anniversary_code;var data={action:'anniversaryChildEmailsBefoerRegistration',ActivationCode:ActivationCode};$.post(the_corporateSubscription_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();var parsedresponse=$.parseJSON(response);if(parsedresponse.msg=='Plan_Deactivated'){jQuery('#child-anniversary-plan-deactivation-modal').modal('show');}
else if(parsedresponse.msg=='New_Email'&&parsedresponse.email){$('#social-login').css('text-align','center').addClass('mr-b-50 p-small').text('Almost done. You will need to create an account with The Ken to claim your free subscription. Once this is done, you will have complete access to our stories for a month.');$('notice-info-icon-register').text('By registering, you will be signed-up for an account which grants you full access to for a limited period. On expiration, this will become an account which will give you access to a free story published once a week, archives of all our free stories, and our daily newsletter. To unsubscribe, please visit the profile section in your account.');$('#social-login').next('.mr-bt-30.txt-upper.txt-center').hide();$('.modal-register-form input[name="user_email"] ').val(parsedresponse.email).prop('readonly',true).css('background','rgba(234, 234, 234, 0.43);');jQuery('#register-modal').modal('show');$('.main_register_form').val('');$('.corporate_ip_user').val('');}
else if(parsedresponse.msg=='Exists_Email'&&parsedresponse.email){var msg=parsedresponse.msg;var email=parsedresponse.email;jQuery('#activating-membership-creation-modal').modal('show');var data1={action:'anniversaryChildEmailsAfterRegistration',msg:msg,email:email};$.post(the_corporateSubscription_response_ajax_script.ajaxurl,data1,function(response1){response1=response1.slice(0,-1).trim();if(response1=='Updated'){jQuery('#activating-membership-creation-modal').modal('hide');jQuery('#anniversary-plan-assinged').modal('show');setTimeout(function(){jQuery('#anniversary-plan-assinged').modal('hide');document.location=String(document.location).replace(/\?.*$/,'');},2500);}else if(response1=='Show_login'){jQuery('#activating-membership-creation-modal').modal('hide');jQuery('#anniversary-plan-assinged').modal('show');setTimeout(function(){jQuery('#anniversary-plan-assinged').modal('hide');jQuery('#login-modal').modal('show');},2500);}});}
else if(parsedresponse.msg=='Exists_member'&&parsedresponse.email){jQuery('#anniversary-plan-assinged').modal('show');$('#anniversary-plan-assinged #verification_notice').text('Oops. Something went wrong. This invite has either expired or been claimed by another user.');setTimeout(function(){jQuery('#anniversary-plan-assinged').modal('hide');jQuery('#login-modal').modal('show');},3000);}
else if(parsedresponse.msg=='Code_Not_Match'){$('#anniversary-plan-assinged').modal('show');$('#anniversary-plan-assinged #verification_notice').text('Oops. Something went wrong. This invite has either expired or been claimed by another user.');setTimeout(function(){jQuery('#anniversary-plan-assinged').modal('hide');jQuery('#register-modal').modal('show');},3000);}
else if(parsedresponse.msg=='Code_Expired'&&parsedresponse.email){jQuery('#aanniversary-plan-assinged').modal('show');jQuery('#anniversary-plan-assinged #verification_notice').text('Oops. Something went wrong. This invite has either expired or been claimed by another user.');setTimeout(function(){jQuery('#anniversary-plan-assinged').modal('hide');jQuery('#register-modal').modal('show');},3000);}});}
if(urlQueryString.anniversary_code&&urlQueryString.accountCreated==1){var ActivationCode=urlQueryString.anniversary_code;var data={action:'anniversaryChildEmailsAfterRegistration',msg:'New_Email',ActivationCode:ActivationCode};$.post(the_corporateSubscription_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();if(response=='Updated'){jQuery('#anniversary-plan-assinged').modal('show');setTimeout(function(){jQuery('#anniversary-plan-assinged').modal('hide');document.location=String(document.location).replace(/\?.*$/,'');},2500);}});}
$(document).delegate("a.multiple_emails-close","click",function(){var getInvites=$('.invites_left').text();var totalInvites=parseInt(getInvites)+1;$('.invites_left').text(totalInvites);$('.error_email').text(' ');});if(urlQueryString.uaXZlcnNhcnlf){var openUrlCode=urlQueryString.uaXZlcnNhcnlf;if(openUrlCode=='YW5uaXZlcnNhcnlfY29kZQ'){jQuery('#random-share-deactive-modal').modal('show');}}
$(".annivarsery-share-register-form .btn-primary").click(function(e){e.preventDefault();var shareEmail=jQuery('.annivarsery-share-register-form input[name="user_email"]').val();$(this).parent().addClass('loadingcopactiry');function validateEmail(sEmail){var filter=/^((\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*)\s*[,]{0,1}\s*)+$/;if(filter.test(sEmail)){return true;}
else{return false;}}
if(shareEmail==""){$('.annivarsery-share-register-form .error_msg').text('THIS FIELD IS REQUIRED.');$('.annivarsery-share-register-form input[name="user_email"]').addClass('error');$(this).parent().removeClass('loadingcopactiry');}
else if((!validateEmail(shareEmail))){$('.annivarsery-share-register-form .error_msg').text('PLEASE ENTER A VALID EMAIL ADDRESS.');$('.annivarsery-share-register-form input[name="user_email"]').addClass('error');$(this).parent().removeClass('loadingcopactiry');}
else{$('.annivarsery-share-register-form .error_msg').text('');$('.annivarsery-share-register-form input[name="user_email"]').removeClass('error');var data={action:'checkExistingShare',shareEmail:shareEmail,};$.post(the_thekentokenization_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();if(response=='Exist_user'){$('.annivarsery-share-register-form .error_msg').text('Sorry, the address '+shareEmail+' belongs to an existing subscriber.');$(".annivarsery-share-register-form .btn-primary").parent().removeClass('loadingcopactiry');$('.annivarsery-share-register-form input[name="user_email"]').addClass('error');}
else{$('.annivarsery-share-register-form .error_msg').text('');$(".annivarsery-share-register-form .btn-primary").parent().removeClass('loadingcopactiry');$('.annivarsery-share-register-form input[name="user_email"]').removeClass('error');jQuery('#anniversary-plan-share-email-box').modal('hide');$('#random-share-verication-modal p.verification_notice').text('Almost done. A confirmation email has been sent to '+shareEmail+'. Click on the link in the email to activate your free subscription.');jQuery('#random-share-verication-modal').modal('show');}});}});if(urlQueryString.random_share&&!urlQueryString.accountCreated){var ActivationCode=urlQueryString.random_share;var data={action:'randomShareEmailsBefoerRegistration',ActivationCode:ActivationCode};$.post(the_corporateSubscription_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();var parsedresponse=$.parseJSON(response);if(parsedresponse.msg=='Plan_Deactivated'){jQuery('#anniversary-plan-assinged').modal('show');$('#anniversary-plan-assinged #verification_notice').text('Oops. Something went wrong. This plan is no longer active. To proceed, do check out and purchase one of our subscription plans.');setTimeout(function(){jQuery('#anniversary-plan-assinged').modal('hide');},3000);}
else if(parsedresponse.msg=='New_Email'&&parsedresponse.email){$('#social-login').css('text-align','center').addClass('mr-b-50 p-small').text('Almost done. You will need to create an account with The Ken to claim your free subscription. Once this is done, you will have complete access to our stories for a month.');$('notice-info-icon-register').text('By registering, you will be signed-up for an account which grants you full access to for a limited period. On expiration, this will become an account which will give you access to a free story published once a week, archives of all our free stories, and our daily newsletter. To unsubscribe, please visit the profile section in your account.');$('#social-login').next('.mr-bt-30.txt-upper.txt-center').hide();jQuery('.modal-register-form input[name="user_email"] ').val(parsedresponse.email).prop('readonly',true).css('background','rgba(234, 234, 234, 0.43);');jQuery('#register-modal').modal('show');$('.main_register_form').val('');$('.corporate_ip_user').val('');}
else if(parsedresponse.msg=='Exists_Email'&&parsedresponse.email){var msg=parsedresponse.msg;var email=parsedresponse.email;jQuery('#activating-membership-creation-modal').modal('show');var data1={action:'randomShareEmailsAfterRegistration',msg:msg,email:email};$.post(the_corporateSubscription_response_ajax_script.ajaxurl,data1,function(response1){response1=response1.slice(0,-1).trim();if(response1=='Updated'){jQuery('#activating-membership-creation-modal').modal('hide');jQuery('#anniversary-plan-assinged').modal('show');setTimeout(function(){jQuery('#anniversary-plan-assinged').modal('hide');document.location=String(document.location).replace(/\?.*$/,'');},2500);}else if(response1=='Show_login'){jQuery('#activating-membership-creation-modal').modal('hide');jQuery('#anniversary-plan-assinged').modal('show');setTimeout(function(){jQuery('#anniversary-plan-assinged').modal('hide');jQuery('#login-modal').modal('show');},2500);}});}
else if(parsedresponse.msg=='Exists_member'&&parsedresponse.email){jQuery('#anniversary-plan-assinged').modal('show');$('#anniversary-plan-assinged #verification_notice').text('Oops. Something went wrong. This invite has either expired or been claimed by another user.');setTimeout(function(){jQuery('#anniversary-plan-assinged').modal('hide');jQuery('#login-modal').modal('show');},3000);}
else if(parsedresponse.msg=='Code_Not_Match'){jQuery('#anniversary-plan-assinged').modal('show');$('#anniversary-plan-assinged #verification_notice').text('Oops. Something went wrong. This invite has either expired or been claimed by another user.');setTimeout(function(){jQuery('#anniversary-plan-assinged').modal('hide');jQuery('#register-modal').modal('show');},3000);}
else if(parsedresponse.msg=='Code_Expired'&&parsedresponse.email){jQuery('#aanniversary-plan-assinged').modal('show');jQuery('#anniversary-plan-assinged #verification_notice').text('Oops. Something went wrong. This invite has either expired or been claimed by another user.');setTimeout(function(){jQuery('#anniversary-plan-assinged').modal('hide');jQuery('#register-modal').modal('show');},3000);}});}
if(urlQueryString.random_share&&urlQueryString.accountCreated==1){var ActivationCode=urlQueryString.random_share;var data={action:'randomShareEmailsAfterRegistration',msg:'New_Email',ActivationCode:ActivationCode};$.post(the_corporateSubscription_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();if(response=='Updated'){jQuery('#anniversary-plan-assinged').modal('show');setTimeout(function(){jQuery('#anniversary-plan-assinged').modal('hide');document.location=String(document.location).replace(/\?.*$/,'');},2500);}});}});jQuery(document).ready(function($){var urlQueryString={};window.location.search.substr(1).split("&").forEach(function(item){urlQueryString[item.split("=")[0]]=item.split("=")[1]});if($('body').attr('data-current-user-id')!=0&&$('body').hasClass("home")){var data={action:'showShareWelcomeModal',};$.post(the_corporateSubscription_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();if(response==='share_welcome'){jQuery('#shared_article_welcome_modal_new').modal('show');}});}
if(urlQueryString.sc&&!urlQueryString.accountCreated&&!urlQueryString.signup_activation){var ActivationCode=urlQueryString.sc;var ShareType=urlQueryString.st;jQuery('#shared-article-assinging').modal('show');var data={action:'articleShareingEmailBefoerRegistration',ActivationCode:ActivationCode,ShareType:ShareType};$.post(the_corporateSubscription_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();console.log(response);var parsedresponse=$.parseJSON(response);if(parsedresponse.msg=='Shared_Plan_Deactivated'){jQuery('#shared-article-assinging').modal('show');setTimeout(function(){jQuery('#shared-article-assinging').modal('hide');},5000);$('#share-article-email-addres-modal .gift-header-msg').html('<h2>Oops. Something went wrong.<br/> This invite has either expired or been claimed by another user.</h2>');$('#share-article-email-addres-modal .form_warraper').addClass('hide')}
else if(parsedresponse.msg=='Shared_New_Email'&&parsedresponse.email){jQuery('#shared-article-assinging').modal('hide');$('.modal-register-form input[name="user_email"] ').val(parsedresponse.email).prop('readonly',true).css('background','rgba(234, 234, 234, 0.43);');$('#share-article-email-addres-modal input[type="email"] ').val(parsedresponse.email);$('.main_register_form').val('');$('.corporate_ip_user').val('');}
else if(parsedresponse.msg=='Shared_New_Email'&&parsedresponse.email==''){jQuery('#shared-article-assinging').modal('hide');$('#register-modal input[name="sc"]').val(ActivationCode);}
else if(parsedresponse.msg=='Shared_Exists_Email'&&parsedresponse.email){var msg=parsedresponse.msg;var email=parsedresponse.email;jQuery('#shared-article-assinging').modal('show');var data1={action:'articleShareingEmailAfterRegistration',ActivationCode:ActivationCode};$.post(the_corporateSubscription_response_ajax_script.ajaxurl,data1,function(response1){response1=response1.slice(0,-1).trim();if(response1=='Shared_Updated'){var story_url=$('#story_url').val();location.href=story_url;}else if(response1=='Shared_Show_login'){jQuery('#shared-article-assinging').modal('show');setTimeout(function(){jQuery('#shared-article-assinging').modal('hide');$('#login-modal input[name="email"] ').val(parsedresponse.email).prop('readonly',true).css('background','rgba(234, 234, 234, 0.43);');jQuery('#login-modal').modal('show');},2500);}});}
else if(parsedresponse.msg=='Shared_Exists_member'&&parsedresponse.email){jQuery('#shared-article-assinging').modal('show');$('#shared-article-assinging .loading-button').addClass('hide');setTimeout(function(){jQuery('#shared-article-assinging').modal('hide');jQuery('#login-modal').modal('show');},3000);$('#share-article-email-addres-modal .gift-header-msg').html('<h2>Oops. Something went wrong.<br/> This invite has either expired or been claimed by another user.</h2>');$('#share-article-email-addres-modal .form_warraper').addClass('hide');}
else if(parsedresponse.msg=='Shared_Code_Not_Match'){jQuery('#shared-article-assingingd').modal('show');$('#shared-article-assinging .loading-button').addClass('hide');setTimeout(function(){jQuery('#shared-article-assinging').modal('hide');},3000);$('#share-article-email-addres-modal .gift-header-msg').html('<h2>Oops. Something went wrong.<br/> This invite has either expired or been claimed by another user.</h2>');$('#share-article-email-addres-modal .form_warraper').addClass('hide');}
else if(parsedresponse.msg=='Shared_Code_Expired'){jQuery('#shared-article-assinging').modal('show');$('#shared-article-assinging .loading-button').addClass('hide');setTimeout(function(){jQuery('#shared-article-assinging').modal('hide');},3000);$('#share-article-email-addres-modal .gift-header-msg').html('<h2>Oops. Something went wrong.<br/> This invite has either expired or been claimed by another user.</h2>');$('#share-article-email-addres-modal .form_warraper').addClass('hide');}});}
if(urlQueryString.sc&&urlQueryString.accountCreated==1){var ActivationCode=urlQueryString.sc;var data={action:'articleShareingEmailAfterRegistration',ActivationCode:ActivationCode};$.post(the_corporateSubscription_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();console.log(response);if(response=='Shared_Updated'){if($('#story_url').length){var story_url=$('#story_url').val();location.href=story_url;}else{document.location=String(document.location).replace(/\?.*$/,'');}}});}
$.fn.share_article_multile_email=function(options){var defaults={checkDupEmail:true,theme:"Bootstrap",position:"top"};var settings=$.extend({},defaults,options);var deleteIconHTML="";if(settings.theme.toLowerCase()=="Bootstrap".toLowerCase())
{deleteIconHTML='<a href="#" class="multiple_emails-close" title="Remove"><span class="glyphicon glyphicon-remove"></span></a>';}
else if(settings.theme.toLowerCase()=="SemanticUI".toLowerCase()||settings.theme.toLowerCase()=="Semantic-UI".toLowerCase()||settings.theme.toLowerCase()=="Semantic UI".toLowerCase()){deleteIconHTML='<a href="#" class="multiple_emails-close" title="Remove"><i class="remove icon"></i></a>';}
else if(settings.theme.toLowerCase()=="Basic".toLowerCase()){deleteIconHTML='<a href="#" class="multiple_emails-close" title="Remove"><i class="basicdeleteicon">x</i></a>';}
return this.each(function(){var $orig=$(this);var $list=$('<ul class="multiple_emails-ul" />');if($(this).val()!=''&&IsJsonString($(this).val())){$.each(jQuery.parseJSON($(this).val()),function(index,val){$list.append($('<li class="multiple_emails-email"><span class="email_name" data-email="'+val.toLowerCase()+'">'+val+'</span></li>').prepend($(deleteIconHTML).click(function(e){$(this).parent().remove();refresh_emails();e.preventDefault();})));});}
var $input=$('<input type="text" class="share_article_multiple_emails-input text-left" text-left" placeholder="Enter one or more email addresses"/>').on('keyup',function(e){$(this).removeClass('multiple_emails-error');$('.share_emals_wrapper .error_email').text('');$('#share_article').removeClass('disabled');var input_length=$(this).val().length;var keynum;if(window.event){keynum=e.keyCode;}
else if(e.which){keynum=e.which;}
if(keynum==9||keynum==32||keynum==188){display_email($(this),settings.checkDupEmail,'0');}
else if(keynum==13){display_email($(this),settings.checkDupEmail,'0');e.preventDefault();}});$("#share_article").click(function(e){e.preventDefault();$('#share_article').addClass('loader-overlay');$(this).addClass('disabled');var share_emails=$('#share_article_emails').val();var multiple_emails=$('.share_article_multiple_emails-input').val();$('.share_emals_wrapper p.error_email').text('');function validateEmail(sEmail){var filter=/^((\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*)\s*[,]{0,1}\s*)+$/;if(filter.test(sEmail)){return true;}else{return false;}}
if($('.share_article_multiple_emails-input').val()!=''){if((!validateEmail(multiple_emails))){jQuery('.share_emals_wrapper .error_email').text('INVALID EMAIL ADDRESS');jQuery('.share_article_multiple_emails-input').addClass('multiple_emails-error');jQuery('#share_article').removeClass('loader-overlay');}
else{display_email($('.share_article_multiple_emails-input'),settings.checkDupEmail,'1');}}
else{if(share_emails.length==0||share_emails.length<3){if(multiple_emails==''){jQuery('.share_emals_wrapper .error_email').text('THIS IS REQUIRED FIELD');jQuery('.share_article_multiple_emails-input').addClass('multiple_emails-error');jQuery('#share_article').removeClass('loader-overlay');}}
else{funSendShareArtcileEmail();}}});var $container=$('<div class="multiple_emails-container" />').click(function(){$input.focus();});if(settings.position.toLowerCase()==="top")
$container.append($list).append($input).insertAfter($(this));else
$container.append($input).append($list).insertBefore($(this));function display_email(t,dupEmailCheck,test){var checklength=$(".multiple_emails-ul").find("li").length;var get_share_emails=jQuery('.share_article_multiple_emails-input').val();var get_selected_share_article=$('#selected_share_article').val();var credit_main=$('.credit_main').text();var resval;var arr=t.val().trim().replace(/^,|,$/g,'').replace(/^;|;$/g,'');arr=arr.replace(/"/g,"");arr=arr.split(/[\s,;]+/);var errorEmails=new Array();var pattern=new RegExp(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i);for(var i=0;i<arr.length;i++){if(dupEmailCheck===true&&$orig.val().indexOf(arr[i])!=-1){if(arr[i]&&arr[i].length>0){new function(){var existingElement=$list.find('.email_name[data-email='+arr[i].toLowerCase().replace('.','\\.').replace('@','\\@')+']');existingElement.css('font-weight','bold');setTimeout(function(){existingElement.css('font-weight','');},1500);}();}}
else if(checklength>=credit_main){jQuery('#share_article_existing_email').val('');jQuery('.share_emals_wrapper p.error_email').text('You can only gift to '+checklength+' people with your remaining gift credits');jQuery('#share_article').removeClass('loader-overlay');}
else if(pattern.test(arr[i])==true){$list.append($('<li class="multiple_emails-email"><span class="email_name" data-email="'+arr[i].toLowerCase()+'">'+arr[i]+'</span></li>').prepend($(deleteIconHTML).click(function(e){$(this).parent().remove();refresh_emails();e.preventDefault();})));$('.share_emals_wrapper span.bottom_shre_consume').removeClass('hide');$('.share_emals_wrapper span.credit_initial').addClass('hide');$('.share_emals_wrapper span.share_email_instruction').addClass('hide');var getInvites=$('.share_emals_wrapper .bottom_shre_consume .credit_consume').text();var getInvites=parseInt(getInvites)+parseInt(1);$('.share_emals_wrapper .bottom_shre_consume .credit_consume').text(getInvites);if(getInvites>1){$('.share_emals_wrapper .bottom_shre_consume .credit_consume_text').text("credits");}else{$('.share_emals_wrapper .bottom_shre_consume .credit_consume_text').text("credit");}
$('.multiple_emails-ul').animate({scrollTop:$('.multiple_emails-ul li').position().top},'slow');if(test==='1'||test===1){funSendShareArtcileEmail()}}
else{errorEmails.push(arr[i]);}}
if(errorEmails.length>0){t.val(errorEmails.join("; ")).addClass('multiple_emails-error');}
else{t.val("");refresh_emails();}}
function funSendShareArtcileEmail(){setTimeout(function(){var share_article_emails=$('#share_article_emails').val();var multiple_emails=$('.share_article_multiple_emails-input').val()
var get_selected_share_article=$('#selected_share_article').val();array=JSON.parse('['+share_article_emails+']'),share_article_emails=array.map(function(a){return a;}).join();var data={action:'sendSharedArticleChildEmail',share_article_emails:share_article_emails,get_selected_share_article:get_selected_share_article};$.post(the_thekentokenization_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();responseJson=JSON.parse(response);$('#share_article').removeClass('loader-overlay');if(responseJson.status=='Mail_Send'){$('#share_free_article_emails').val('');$('.share_article_multiple_emails-input').val('')
$('#share_article_emails').val('');$('.multiple_emails-ul').text('');$('.bottom_shre_consume').addClass('hide');$('.bottom_shre_consume .credit_consume').text('0');$('.credit_main').text(responseJson.credit_left);$('.credit_left').text(responseJson.credit_left);$('#shared_article_parent_success-modal .credit_parent_main .left_parent_credit').text(responseJson.credit_left);$('.notification-band-content .notification-share-count-left').text(responseJson.credit_left);if(responseJson.credit_left==0){$('#shared_article_parent_success-modal a.share_more_gift').addClass('hide');$('#shared_article_parent_success-modal button.request_for_credit').removeClass('hide');$('.no-story-credit').removeClass('hide');$('.main_gift_wrpper').addClass('hide');$('#shared_article_parent_modal_new h2').text('Dang, you’re out of credits');}else{$('#shared_article_parent_success-modal a.share_more_gift').removeClass('hide');$('#shared_article_parent_success-modal button.request_for_credit').addClass('hide');}
jQuery('#shared_article_parent_modal_new').modal('hide');jQuery('#shared_article_parent_success-modal').modal('show');$('.share_emals_wrapper span.credit_initial').removeClass('hide');var total=$('#SEA_story_credit_total').val();var active=responseJson.credit_left
var remaing=parseInt(total)-parseInt(active);jQuery('.gift-block').html('');for(var i=0;i<total;i++){if(i<remaing){jQuery('.gift-block').append('<span class="giftFill"></span>');}
else{jQuery('.gift-block').append('<span class="giftEmpty"></span>');}}}});},2000);}
function refresh_emails(){var emails=new Array();var container=$orig.siblings('.multiple_emails-container');container.find('.multiple_emails-email span.email_name').each(function(){emails.push($(this).html());});$orig.val(JSON.stringify(emails)).trigger('change');}
function IsJsonString(str){try{JSON.parse(str);}
catch(e){return false;}
return true;}
return $(this).hide();});};$(document).delegate("a.multiple_emails-close","click",function(){var checklength=$(".multiple_emails-ul").find("li").length;if(checklength<=0){$('span.bottom_shre_consume').addClass('hide');$('.share_emals_wrapper span.credit_initial').removeClass('hide');$('.share_emals_wrapper span.share_email_instruction').removeClass('hide');}
var getInvites=$('.share_emals_wrapper .credit_consume').text();var totalInvites=parseInt(getInvites)-1;$('.share_emals_wrapper .credit_consume').text(totalInvites);$('.share_emals_wrapper .error_email').text(' ');if(getInvites>1){$('.share_emals_wrapper .bottom_shre_consume .credit_consume_text').text("credits");}else{$('.share_emals_wrapper .bottom_shre_consume .credit_consume_text').text("credit");}});$('#share_article_emails').share_article_multile_email({theme:"Basic"});$('#share_article_emails').text($('#share_article_emails').val());$("#generate_link").click(function(e){e.preventDefault();var get_selected_share_article=$('#selected_share_article').val();var credit_main=$('.credit_main').text();var update_main_credit=0;$('#generate_link').addClass('loader-overlay');$('#generate_link').addClass('disabled');$('#sharecode').val('');$('.generate_link_wrapper .copy_url').addClass('hide');var data={action:'geneartationSharedArticle',get_selected_share_article:get_selected_share_article};$.post(the_thekentokenization_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();responseJson=JSON.parse(response);$('#generate_link').removeClass('loader-overlay');if(responseJson.status=='limit_exceed'){$('#generate_link').removeClass('disabled');$('.share-input-container').html(`<div class="share-input-container-inner share_emals_wrapper zero-credits"><h3 class="mr-t-0">You’re out of credits, sigh…</h3><p>Our stories are exclusively for our subscribers. We put in a lot of effort and resources in writing our stories and believe that one must pay for good journalism. To this end, we currently limit gifting of stories.</p><p class="mr-b-15">Your credit balance will be topped up on the 1st of every month allowing you to gift more. Under certain circumstances, users may be able to buy more credits.</p><button class="btn-primary request_for_credit" style="width: 100%; font-weight: bold;">Request to buy more credits</button></div>`);}
else if(responseJson.status!='error'){jQuery('#send-email-modal').modal('hide');jQuery('#generate-link-modal').modal('show');$('#sharecode').val(responseJson.tokenize_url);$('.generate_link_instruction').html('<i>Done! Share this link to allow 1 subscriber access to the story</i>');$('.credit_main').text(responseJson.credit_left);$('.credit_left').text(responseJson.credit_left);$('.generate_link_wrapper .copy_url').removeClass('hide');$('.notification-band-content .notification-share-count-left').text(responseJson.credit_left);$('.generate_link_wrapper #generate_link').text('Create another gift link');$('#generate_link').removeClass('disabled');if(responseJson.credit_left==0){$('.no-story-credit').removeClass('hide');$('.main_gift_wrpper').addClass('hide');$('#shared_article_parent_modal_new h2').text('Dang, you’re out of credits');}
var total=$('#SEA_story_credit_total').val();var active=responseJson.credit_left
var remaing=parseInt(total)-parseInt(active);jQuery('.gift-block').html('');for(var i=0;i<total;i++){if(i<remaing){jQuery('.gift-block').append('<span class="giftFill"></span>');}
else{jQuery('.gift-block').append('<span class="giftEmpty"></span>');}}}});});$(".article-share-trigger").click(function(e){e.preventDefault();var data_article_id=$(this).attr('data-article-id');window.location.href=window.location.href+"/?p="+data_article_id+"&modal=article_sharing";});$(".request_for_credit").click(function(e){e.preventDefault();$(this).addClass('disabled');jQuery('#request-credit-success-modal').modal('show');jQuery('#shared_article_parent_modal_new').modal('hide');jQuery('#shared_article_parent_success-modal').modal('hide');});if(urlQueryString.fsc&&!urlQueryString.signup_activation){var ActivationCode=urlQueryString.fsc;var ArticleID=$('#article_post_id').val();var Isfree=$('#free_reads').val();$('#register-modal input[name="fsc"]').val(ActivationCode);jQuery('#shared-article-assinging').modal('show');var data={action:'freeArticleSharing',ActivationCode:ActivationCode,ArticleID:ArticleID,Isfree:Isfree};$.post(the_corporateSubscription_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();console.log(response);if(response=='show_login'){jQuery('#shared-article-assinging').modal('hide');jQuery('#login-modal').modal('show');}else if(response=='show_register'){jQuery('#shared-article-assinging').modal('hide');jQuery('#register-modal').modal('show');}
else if(response=='show_free_capture'){jQuery('#shared-article-assinging').modal('hide');}else{var story_url=$('#story_url').val();location.href=story_url;}});}
if(urlQueryString.fsc&&urlQueryString.accountCreated==1){var ActivationCode=urlQueryString.fsc;var ArticleID=$('#article_post_id').val();var Isfree=$('#free_reads').val();$('#register-modal input[name="fsc"]').val(ActivationCode);jQuery('#shared-article-assinging').modal('show');var data={action:'freeArticleSharing',ActivationCode:ActivationCode,ArticleID:ArticleID,Isfree:Isfree};$.post(the_corporateSubscription_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();console.log(response);if($('#story_url').length){var story_url=$('#story_url').val();location.href=story_url;}else{document.location=String(document.location).replace(/\?.*$/,'');}});}
$.fn.share_free_article_multile_email=function(options){var defaults={checkDupEmail:true,theme:"Bootstrap",position:"top"};var settings=$.extend({},defaults,options);var deleteIconHTML="";if(settings.theme.toLowerCase()=="Bootstrap".toLowerCase())
{deleteIconHTML='<a href="#" class="multiple_emails-close" title="Remove"><span class="glyphicon glyphicon-remove"></span></a>';}
else if(settings.theme.toLowerCase()=="SemanticUI".toLowerCase()||settings.theme.toLowerCase()=="Semantic-UI".toLowerCase()||settings.theme.toLowerCase()=="Semantic UI".toLowerCase()){deleteIconHTML='<a href="#" class="multiple_emails-close" title="Remove"><i class="remove icon"></i></a>';}
else if(settings.theme.toLowerCase()=="Basic".toLowerCase()){deleteIconHTML='<a href="#" class="multiple_emails-close" title="Remove"><i class="basicdeleteicon">x</i></a>';}
return this.each(function(){var $orig=$(this);var $list=$('<ul class="multiple_emails-ul" />');if($(this).val()!=''&&IsJsonString($(this).val())){$.each(jQuery.parseJSON($(this).val()),function(index,val){$list.append($('<li class="multiple_emails-email"><span class="email_name" data-email="'+val.toLowerCase()+'">'+val+'</span></li>').prepend($(deleteIconHTML).click(function(e){$(this).parent().remove();refresh_emails();e.preventDefault();})));});}
var $input=$('<input type="text" class="share_free_article_multiple_emails-input text-left" text-left" placeholder="Enter one or more email addresses"/>').on('keyup',function(e){$(this).removeClass('multiple_emails-error');$('.share_free_emals_wrapper .error_email').text('');$('#share_free_article').removeClass('disabled');var input_length=$(this).val().length;var keynum;if(window.event){keynum=e.keyCode;}
else if(e.which){keynum=e.which;}
if(keynum==9||keynum==32||keynum==188){display_email($(this),settings.checkDupEmail,'0');}
else if(keynum==13){display_email($(this),settings.checkDupEmail,'0');e.preventDefault();}});$("#share_free_article").click(function(e){e.preventDefault();$('#share_free_article').addClass('loader-overlay');$(this).addClass('disabled');var share_emails=$('#share_free_article_emails').val();var multiple_emails=$('.share_free_article_multiple_emails-input').val();function validateEmail(sEmail){var filter=/^((\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*)\s*[,]{0,1}\s*)+$/;if(filter.test(sEmail)){return true;}else{return false;}}
if($('.share_free_article_multiple_emails-input').val()!=''){if((!validateEmail(multiple_emails))){jQuery('.share_free_emals_wrapper .error_email').text('INVALID EMAIL ADDRESS');jQuery('.share_free_article_multiple_emails-input').addClass('multiple_emails-error');jQuery('#share_free_article').removeClass('loader-overlay');}
else{display_email($('.share_free_article_multiple_emails-input'),settings.checkDupEmail,'1');}}
else{if(share_emails.length==0||share_emails.length<3){if(multiple_emails==''){jQuery('.share_free_emals_wrapper .error_email').text('THIS IS REQUIRED FIELD');jQuery('.share_free_article_multiple_emails-input').addClass('multiple_emails-error');jQuery('#share_free_article').removeClass('loader-overlay');}}
else{funSendShareFreeArtcileEmail();}}});var $container=$('<div class="multiple_emails-container" />').click(function(){$input.focus();});if(settings.position.toLowerCase()==="top")
$container.append($list).append($input).insertAfter($(this));else
$container.append($input).append($list).insertBefore($(this));function display_email(t,dupEmailCheck,test){var checklength=$(".multiple_emails-ul").find("li").length;var get_share_emails=jQuery('.share_free_article_multiple_emails-input').val();var get_selected_share_article=$('#selected_free_share_article').val();var arr=t.val().trim().replace(/^,|,$/g,'').replace(/^;|;$/g,'');arr=arr.replace(/"/g,"");arr=arr.split(/[\s,;]+/);var errorEmails=new Array();var pattern=new RegExp(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i);for(var i=0;i<arr.length;i++){if(dupEmailCheck===true&&$orig.val().indexOf(arr[i])!=-1){if(arr[i]&&arr[i].length>0){new function(){var existingElement=$list.find('.email_name[data-email='+arr[i].toLowerCase().replace('.','\\.').replace('@','\\@')+']');existingElement.css('font-weight','bold');setTimeout(function(){existingElement.css('font-weight','');},1500);}();}}
else if(pattern.test(arr[i])==true){$list.append($('<li class="multiple_emails-email"><span class="email_name" data-email="'+arr[i].toLowerCase()+'">'+arr[i]+'</span></li>').prepend($(deleteIconHTML).click(function(e){$(this).parent().remove();refresh_emails();e.preventDefault();})));$('.multiple_emails-ul').animate({scrollTop:$('.multiple_emails-ul li').position().top},'slow');if(test==='1'||test===1){funSendShareFreeArtcileEmail()}}
else{errorEmails.push(arr[i]);}}
if(errorEmails.length>0){t.val(errorEmails.join("; ")).addClass('multiple_emails-error');}
else{t.val("");refresh_emails();}}
function funSendShareFreeArtcileEmail(){setTimeout(function(){var share_article_emails=$('#share_free_article_emails').val();var multiple_emails=$('.share_free_article_multiple_emails-input').val()
var get_selected_share_article=$('#selected_share_article').val();array=JSON.parse('['+share_article_emails+']'),share_article_emails=array.map(function(a){return a;}).join();var data={action:'sendSharedFreeArticleChildEmail',share_article_emails:share_article_emails,get_selected_share_article:get_selected_share_article};$.post(the_thekentokenization_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();$('#share_free_article').removeClass('loader-overlay');if(response=='Mail_Send'){jQuery('#shared_article_parent_modal_new').modal('hide');$('#share_free_article_emails').val('');$('.share_free_article_multiple_emails-input').val('')
$('.multiple_emails-ul').text('');$('#shared_article_parent_success-modal a.share_more_gift').removeClass('hide');$('#shared_article_parent_success-modal button.request_for_credit').addClass('hide');jQuery('#shared_article_parent_success-modal').modal('show');$('#shared_article_parent_success-modal .credit_parent_main').addClass('hide');}});},2000);}
function refresh_emails(){var emails=new Array();var container=$orig.siblings('.multiple_emails-container');container.find('.multiple_emails-email span.email_name').each(function(){emails.push($(this).html());});$orig.val(JSON.stringify(emails)).trigger('change');}
function IsJsonString(str){try{JSON.parse(str);}
catch(e){return false;}
return true;}
return $(this).hide();});};$('#share_free_article_emails').share_free_article_multile_email({theme:"Basic"});$('#share_free_article_emails').text($('#share_free_article_emails').val());$('.resend_story_share_email').click(function(){var data_id=$(this).attr('data-id');$(this).addClass('disabled');var data={action:'resendSharedArticleChildEmail',data_id:data_id};$(this).addClass('loader-overlay');$.post(the_thekentokenization_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();jQuery('#general-success-meaage-modal').modal('show');$('#general-success-meaage-modal p').text('Email has been sent');setTimeout(function(){jQuery('#general-success-meaage-modal').modal('hide');},2000);$('.resend_story_share_email').removeClass('loader-overlay');});});$('#check_share_article_email').click(function(e){e.preventDefault();var email_address=$('#share-article-email-addres-modal input[type="email"]').val();var article_post_id=$('#article_post_id').val();var paid_share_code="";var free_share_code="";paid_share_code=$('#paid_share_code').val();free_share_code=$('#free_share_code').val();var activationCode=urlQueryString.sc;function validateEmail(sEmail){var filter=/^((\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*)\s*[,]{0,1}\s*)+$/;if(filter.test(sEmail)){return true;}
else{return false;}}
if(email_address==""){$('#share-article-email-addres-modal .error').text('THIS FIELD IS REQUIRED.');$('#share-article-email-addres-modal input[type="email"]').addClass('error');}
else if((!validateEmail(email_address))){$('#share-article-email-addres-modal .error').text('PLEASE ENTER A VALID EMAIL ADDRESS.');$('#share-article-email-addres-modal input[type="email"]').addClass('error');}
else{$('#check_share_article_email').addClass('loader-overlay');var data={action:'check_article_shared_email',email_address:email_address,activationCode:activationCode};$.post(the_thekencustomization_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();if(response=='login'){$('#check_share_article_email').removeClass('loader-overlay');jQuery('#login-modal').modal('show');$('#login-modal .close.modal-close').hide();$('.modal-login-form input[name="email"] ').val(email_address).prop('readonly',true).css({background:'rgba(234, 234, 234, 0.43)',cursor:'not-allowed;'});var get_share_parent_login=$('.show_share_in_login_modal').html();$('#login-modal .modal-login-wrapper .h2').html(get_share_parent_login);$('#login-modal #login-form-btn').addClass('giftee_login');}
else if(response=='register'){$('#check_share_article_email').removeClass('loader-overlay');var get_share_parent_register=$('.show_share_in_register_modal').html();$('#register-modal input[name="current_story"]').val(article_post_id);$('#register-modal input[name="sc"]').val(paid_share_code);$('#register-modal input[name="fsc"]').val(free_share_code);$('#register-modal .h2').html(get_share_parent_register);jQuery('#register-modal').modal('show');$('#register-modal .close.modal-close').hide();$('.modal-register-form input[name="user_email"] ').val(email_address).prop('readonly',true).css({background:'rgba(234, 234, 234, 0.43)',cursor:'not-allowed;'});$('#register-modal #modal-register-btn').addClass('giftee_register');}});}});$('#share-article-email-addres-modal #user_email').click(function(){$('#share-article-email-addres-modal .error').text('');$('#share-article-email-addres-modal #user_email').removeClass('error');});$('.article-share-floating-btn a').click(function(){var main_credit_left=$('span.credit_main').text();$('.generate_link_wrapper .article-share-copy-link1 .copy_url').addClass('hide');$('.generate_link_wrapper .article-share-copy-link1 .loading-button').removeClass('hide');$('.generate_link_wrapper .article-share-copy-link1 #generate_link').removeClass('disabled');$('.generate_link_wrapper  #sharecode').val('');$('.generate_link_instruction').html('<i>This will consume 1 gift credit</i>');$('#shared_article_parent_modal_new .error_email').text('');$('#shared_article_parent_modal_new .bottom_shre_consume .credit_consume').text('0');$('#shared_article_parent_modal_new .bottom_shre_consume').addClass('hide');$('#shared_article_parent_modal_new .multiple_emails-input').val('');$('#shared_article_parent_modal_new .multiple_emails-ul').html('');$('.share_emals_wrapper span.share_email_instruction').removeClass('hide');});$("#share-article-email-addres-modal").keypress(function(e){if(e.keyCode==13){e.preventDefault();$("#check_share_article_email").trigger("click");}});$('.share_more_gift').click(function(){jQuery('#shared_article_parent_success-modal').modal('hide');jQuery('#shared_article_parent_modal_new').modal({show:false,backdrop:'static',keyboard:true});jQuery('#shared_article_parent_modal_new').modal('show');});$("#request-credit-success-modal .gift_request_count").on("change",function(){var val=Math.abs(parseInt(this.value,10)||1);this.value=val>101?100:val;$('#request-credit-success-modal .error_email').text('');});$('#request-credit-success-modal .send_gift_request_count').click(function(){var gift_request_count=$("#request-credit-success-modal .gift_request_count").val();if(gift_request_count==""){$('#request-credit-success-modal .error_email').text('THIS FIELD IS REQUIRED.');}
else{$(this).addClass('loader-overlay');var data={action:'requestForShareCredit',gift_request_count:gift_request_count};$.post(the_thekentokenization_response_ajax_script.ajaxurl,data,function(response){response=response.slice(0,-1).trim();$(this).removeClass('loader-overlay');$("#request-credit-success-modal .send_gift_request_form").addClass('hide');$("#request-credit-success-modal .send_gift_request_success").removeClass('hide');});}});$("#request-credit-success-modal ").keypress(function(e){if(e.keyCode==13){e.preventDefault();$("#request-credit-success-modal .send_gift_request_count").trigger("click");}});$('.generate_link_wrapper').css('right','-106%');$('.share_free_emals_wrapper').css('right','-106%');$('.create_link_wrapper a').on('click',function(){$('.share_emals_wrapper').css('right','106%');$('.generate_link_wrapper').css('right','0%');$('.share_free_emals_wrapper').css('right','-106%');$('.generate_free_link_wrapper').css('right','0%');});$('.create_email_wrapper a').on('click',function(){$('.generate_link_wrapper').css('right','-106%');$('.share_emals_wrapper').css('right','0%');$('.generate_free_link_wrapper').css('right','106%');$('.share_free_emals_wrapper').css('right','0%');});$('.copy_url').mouseleave(function(){$(this).text('Copy Link');});});function copyshareurl(){$('.copy_url').text('Copied');var el=document.getElementById("sharecode");if(navigator.userAgent.match(/ipad|ipod|iphone/i)){var editable=el.contentEditable;var readOnly=el.readOnly;el.contentEditable=true;el.readOnly=true;var range=document.createRange();range.selectNodeContents(el);var selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);el.setSelectionRange(0,999999);el.contentEditable=editable;el.readOnly=readOnly;}else{el.select();}
document.execCommand('copy');}
function copyfreeshareurl(){$('.copy_url').text('Copied');var el=document.getElementById("free_sharecode");if(navigator.userAgent.match(/ipad|ipod|iphone/i)){var editable=el.contentEditable;var readOnly=el.readOnly;el.contentEditable=true;el.readOnly=true;var range=document.createRange();range.selectNodeContents(el);var selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);el.setSelectionRange(0,999999);el.contentEditable=editable;el.readOnly=readOnly;}else{el.select();}
document.execCommand('copy');}